spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_schema
    username: root
    password: klsa2921
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.MySQL8Dialect
    database: mysql

server:
  port: 2921